name: Submission Bot (제출 봇)

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Person to greet"
        required: true
        default: "thdwoqor"
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: '0 2 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
    
    - name: Create env file
      run: |
        touch .env
        echo ADDRESS=${{ secrets.ADDRESS }} >> .env
        echo DORMITORY=${{ secrets.DORMITORY }} >> .env
        echo NAME=${{ secrets.NAME }} >> .env
        echo ID=${{ secrets.ID }} >> .env
        echo ROOM=${{ secrets.ROOM }} >> .env
        echo END=${{ secrets.END }} >> .env
        cat .env

    - name: Run run.py
      run: |
        python run.py
